version: '3.7'
services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    image: app-php
    container_name: app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
    networks:
      - web
      -  db
  
  nginx:
    image: nginx:1.17-alpine
    container_name: nginx
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d
    networks:
      - web

  db:
    image: mariadb:10.5
    container_name: db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: yqhdch
      MYSQL_ROOT_PASSWORD: 63Ft%<B\SRLM(t%/
      MYSQL_PASSWORD: 63Ft%<B\SRLM(t%/
      MYSQL_USER: alejandro
      MARIADB_CHARACTER_SET_SERVER: utf8mb4
      MARIADB_COLLATION_SERVER: utf8mb4_unicode_ci
    networks:
      - db   
      
networks:
  web:
    driver: bridge
  db:
    driver: bridge