insert into ingredients value(null, "Codillo de cerdo preasado");
insert into ingredients value(null, "Mostaza de Dijon");
insert into ingredients value(null, "Tomillo");
insert into ingredients value(null, "Miel");

insert into ingredients value(null, "Aceite vegetal para freír");
insert into ingredients value(null, "Sal cucharada");
insert into ingredients value(null, "Pimienta negra molida");
insert into ingredients value(null, "Bicarbonato sódico");
insert into ingredients value(null, "Ajo en polvo");
insert into ingredients value(null, "Jengibre fresco");
insert into ingredients value(null, "Maicena");
insert into ingredients value(null, "Mantequilla");
insert into ingredients value(null, "Chile rojo fresco o pimienta de cayena al gusto");
insert into ingredients value(null, "Diente de ajo");
insert into ingredients value(null, "Salsa Sriracha o gochujang");
insert into ingredients value(null, "Ketchup");
insert into ingredients value(null, "Vinagre de arroz");
insert into ingredients value(null, "Salsa de soja");
insert into ingredients value(null, "Azúcar moreno");
insert into ingredients value(null, "Cacahuetes");
insert into ingredients value(null, "Cebollino o ajete");
insert into ingredients value(null, "Semillas de sésamo");
