insert into ingredient_recipe value(null, null, null, 1, 1, "2");
insert into ingredient_recipe value(null, null, null, 1, 2, "2 cucharadas");
insert into ingredient_recipe value(null, null, null, 1, 3, "2 cucharadas");
insert into ingredient_recipe value(null, null, null, 1, 4, "");

insert into ingredient_recipe value(null, null, null, 2, 4, "");
insert into ingredient_recipe value(null, null, null, 2, 5, "1 cucharadas");
insert into ingredient_recipe value(null, null, null, 2, 6, "1/2 cucharadas");
insert into ingredient_recipe value(null, null, null, 2, 7, "1/2 cucharadas");
insert into ingredient_recipe value(null, null, null, 2, 8, "1/2 cucharadas");
insert into ingredient_recipe value(null, null, null, 2, 9, "2 cucharadas");
insert into ingredient_recipe value(null, null, null, 2, 10, "80 gr");
insert into ingredient_recipe value(null, null, null, 2, 11, "3 cucharadas");
insert into ingredient_recipe value(null, null, null, 2, 12, "");
insert into ingredient_recipe value(null, null, null, 2, 13, "1 diente");
insert into ingredient_recipe value(null, null, null, 2, 14, "2 cucharadas");
insert into ingredient_recipe value(null, null, null, 2, 15, "2 cucharadas");
insert into ingredient_recipe value(null, null, null, 2, 16, "1cucharadas");
insert into ingredient_recipe value(null, null, null, 2, 17, "1 cucharadas");
insert into ingredient_recipe value(null, null, null, 2, 18, "2 cucharadas");
insert into ingredient_recipe value(null, null, null, 2, 19, "2 cucharadas");
insert into ingredient_recipe value(null, null, null, 2, 20, "");
insert into ingredient_recipe value(null, null, null, 2, 21, "");
insert into ingredient_recipe value(null, null, null, 2, 22, "");